_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 3
                - 13
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
features:
    value:
        - AvgThrottle
        - AvgDRS
        - FuelLoad
        - AvgSpeed
model_type:
    value: RandomForestRegressor
random_state:
    value: 42
test_size:
    value: 0.2
